Add option to make user return to spawn when dies
WiIIiam278/HuskHomes pull request #540
Opened 2023-12-26 17:01 UTC by Yuhtin

This Pull Request resolves the issue #533

2023-12-26 17:25 UTC, WiIIiam278 requested changes
Nice work, just the one comment and if you could update the conifg in `docs/Config-Files.md` that'd be perfect.

2023-12-26 17:25 UTC, WiIIiam278 commented on common/src/main/java/net/william278/huskhomes/config/Settings.java
> +    @YamlKey("general.spawn_command_return_by_death")
I think a better config node for this would be `always_respawn_at_spawn` :)

2023-12-28 05:41 UTC, Yuhtin reviewed
I updated the config in this new commit

2023-12-29 00:41 UTC, WiIIiam278 approved these changes

2023-12-30 10:59 UTC, merged