Update docs to reflect Commit 7ad9104
WiIIiam278/HuskHomes pull request #619
Opened 2024-04-23 18:15 UTC by ProdPreva1l

Update docs to reflect [Commit 7ad9104](https://github.com/WiIIiam278/HuskHomes/commit/7ad91046778acc551d7b2c96f07bd08e431cabab)

2024-04-23 18:15 UTC, ProdPreva1l commented
I really need to learn how to make git not do that

2024-04-23 18:17 UTC, WiIIiam278 requested changes
Can you revert your changes to `Settings.java`?

2024-04-23 18:18 UTC, ProdPreva1l commented
I could swear i did, someone needs to send me a git master class lesson

2024-04-23 18:20 UTC, ProdPreva1l commented
Done

2024-04-24 04:33 UTC, PseudoResonance commented on docs/Database.md
> +      # Specify credentials here if you are using MYSQL, MARIADB, or POSTGRESQ as your database type
There's a typo here in POSTGRESQL

2024-04-24 04:34 UTC, PseudoResonance commented
I just realized I forgot to update the documentation in my change and came here to check, when I saw this. Thanks!

2024-04-24 09:41 UTC, WiIIiam278 approved these changes

2024-04-24 09:42 UTC, merged

2024-04-24 09:42 UTC, WiIIiam278 commented
Something that slipped my mind. Thanks!