Adjusting the permissions node for the /rtp command
WiIIiam278/HuskHomes pull request #626
Opened 2024-05-07 11:39 UTC by alazeprt

Remove the original permission node huskhomes.command.rtp.world and add the permission node huskhomes.command.rtp.<world>, where <world> can be changed to any of the server's worlds, and this permission node can grant the player the permission to be randomly teleported to a specified world

2024-05-07 11:40 UTC, alazeprt commented
Corresponds to issue [#625](https://github.com/WiIIiam278/HuskHomes/issues/625)

2024-05-07 12:01 UTC, WiIIiam278 commented on common/src/main/java/net/william278/huskhomes/command/RtpCommand.java
> +        plugin.getWorlds().forEach(world -> map.put(world.getName(), true));
Can we filter this by `plugin.getSettings().getRtp().isWorldRtpRestricted(world)` (so as to not register unneccessary perms)?

2024-05-09 14:27 UTC, WiIIiam278 requested changes
This looks great, just need the above comment to be addressed :)

2024-05-11 12:03 UTC, alazeprt commented
Resolved in the latest commit

2024-05-11 12:04 UTC, WiIIiam278 approved these changes
Cool, looks great then.

2024-05-11 12:13 UTC, merged